baseurl = "http://devtrax.io/"
languageCode = "en-us"
title = "Devtrax Studio"

theme = "hugo-agency-theme"
# Enter your tracking code to enable Google Analytics
googleAnalytics = "UA-75491060-1"

[params]

	# You can use Markdown syntax for urls [text](//url.to/source) or
	# most longer texts.
	#
	# All icons using Fontawesome's icon font. Look at fortawesome.github.io/Font-Awesome/icons/
	# for more icons. The icons are represented by their corresponding
	# CSS class.

	# To provide some metadata for search engines feel free to add a few
    # information about you and your website.
	name = "Devtrax Studio"
	description = "Development Studio"

	# Since this template is static, the contact form uses www.formspree.io as a
	# proxy. The form makes a POST request to their servers to send the actual
	# email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!
	email = "team@devtrax.io"


	# Navigation
	[params.navigation]
		brand = "Devtrax"
		services = "Services"
		# portfolio = "Portfolio"
		# about = "About"
		team = "Team"
		contact = "Contact"

    # Add custom links. Those can be pre- and postpended to the default menu above.
    # Use the weight attribute to order your custom links. Uncomment the example
    # below and replace the values with your own.

    # prepended links
    #[[menu.prepend]]
    #    url = "http://gohugo.io"
    #    name = "Hugo"
    #    weight = 10

    # postpended links
    # [[menu.postpend]]
    #     url = "http://gohugo.io"
    #     name = "External link"
    #     weight = 10


	# Hero section
	[params.hero]
		# To change the background image of the hero, replace 'header-bg.jpg' in
		# the 'static/img' folder.
		title = "Welcome To Devtrax!"
		subtitle = "Advanced Technical Solutions"
		buttonText = "Tell me more"


	# Services section
	[params.services]
        enable = true
		title = "Services"
		subtitle = "What we can design and develop for you."

        [[params.services.row]]


            [[params.services.row.list]]
                icon = "fa-laptop"
                title = "MDP Development"
								description = "We create Minimal Desirable Products. Using Golang and Reactjs, we can develop functioning beautiful prototypes at incredible speeds that connect with real data and devices."

            [[params.services.row.list]]
                icon = "fa-code"
                title = "Application Development"
                description = "We do end-to-end design and development of web and mobile applicaions. We strive to deliver products that are that are intuitive, fast, and have a touch of design beauty."

            [[params.services.row.list]]
                icon = "fa-lock"
                title = "Systems Development"
                description = "We use technologies such as Golang, Nodejs and PHP to create information systems and automate business processes. We also take care of deployment infrastructure and maintenance."

	# Portfolio section
	[params.portfolio]
        enable = false
		# All projects defined in their own files. You can find example projects
		# at 'exampleSite/data/projects'. Copy the 'projects' folder into the 'data' directory
		# at the root of this Hugo site.
		# For more informtion take a look at the README.
		title = "Portfolio"
		subtitle = "Lorem ipsum dolor sit amet consectetur."

		[params.portfolio.modal]
            client = "Client"
            date = "Date"
            category = "Category"
            buttonText = "Close project"


    # About section
	[params.about]
        enable = false
		title = "About"
		subtitle = "Lorem ipsum dolor sit amet consectetur."
		endpoint = "Be part<br>of our<br>story!"

		# The events will be listed from the top to the bottom.
		# All images are stored under 'static/img/about'.
		# Replace them with your own.
		[[params.about.events]]
			img = "1.jpg"
			date = "2009-2011"
			title = "Our Humble Beginnings"
			description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sunt ut voluptatum eius sapiente, totam reiciendis temporibus qui quibusdam, recusandae sit vero unde, sed, incidunt et ea quo dolore laudantium consectetur!"

		[[params.about.events]]
			img = "2.jpg"
			date = "March 2011"
			title = "An Agency is Born"
			description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sunt ut voluptatum eius sapiente, totam reiciendis temporibus qui quibusdam, recusandae sit vero unde, sed, incidunt et ea quo dolore laudantium consectetur!"

		[[params.about.events]]
			img = "3.jpg"
			date = "December 2012"
			title = "Our Humble Beginnings"
			description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sunt ut voluptatum eius sapiente, totam reiciendis temporibus qui quibusdam, recusandae sit vero unde, sed, incidunt et ea quo dolore laudantium consectetur!"

		[[params.about.events]]
			img = "4.jpg"
			date = "July 2014"
			title = "Phase Two Expansion"
			description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sunt ut voluptatum eius sapiente, totam reiciendis temporibus qui quibusdam, recusandae sit vero unde, sed, incidunt et ea quo dolore laudantium consectetur!"


	# Team section
	[params.team]
        enable = true
		title = "The Team"
		subtitle = "The trio of nerds, here to serve!"
		description = "You're all developers? Yes! We are all developers at heart. But we also do our own design, marketting, sales, and business too!"

		# All team member's pictures are stored under 'static/img/team'.
		# Replace them with your own too.

		[[params.team.members]]
			img = "sont.jpg"
			name = "Daniel Sont"
			position = "Co-founder, Developer"
			social = [
				["fa-twitter", "https://twitter.com/ds0nt"],
				["fa-facebook", "https://www.facebook.com/daniel.sont.75"],
				["fa-linkedin", "https://www.linkedin.com/in/danielsont"]
			]

		[[params.team.members]]
			img = "johnston.jpg"
			name = "Josh Johnston"
			position = "Co-founder, Developer"
			social = [
				# ["fa-twitter", "#"],
				["fa-facebook", "https://www.facebook.com/joshua.johnston.73"],
				# ["fa-linkedin", "#"]
			]

		[[params.team.members]]
			img = "https://datahexagon.com/jeremy/Pylon/Screenshot_92.png"
			name = "Jeremy Evans"
			position = "Co-founder, Developer"
			social = [
				["fa-twitter", "https://twitter.com/SpaceHexagon"],
				["fa-facebook", "https://www.facebook.com/VirtualJer"],
				["fa-linkedin", "https://www.linkedin.com/in/jeremyevans7"]
			]

	# Client section
    [params.clients_list]
        enable = false

    	# All the clients' logos are stored under 'static/img/logos'.
    	# Replace them with your clients's logos.
    	[[params.clients]]
    		logo = "envato.jpg"
    		link = "#"

    	[[params.clients]]
    		logo = "designmodo.jpg"
    		link = "#"

    	[[params.clients]]
    		logo = "themeforest.jpg"
    		link = "#"

    	[[params.clients]]
    		logo = "creative-market.jpg"
    		link = "#"


	# Contact section
	[params.contact]
        enable = true
		title = "Contact us"
		subtitle  = "Inquire about what we can do for you."
		buttonText = "Send message"

		# 'warning' defines error messages for invalid inputs
		[params.contact.form.name]
			text = "Your Name *"
			warning = "Please enter your name."

		[params.contact.form.email]
			text = "Your Email *"
			warning = "Please enter your email address."

		[params.contact.form.phone]
			text = "Your Phone *"
			warning = "Please enter your phone number."

		[params.contact.form.message]
			text = "Your Message *"
			warning = "Please enter a message."


	# Footer section
	[params.footer]
        enable = true
		copyright = ""

		[[params.footer.social]]
			icon = "fa-twitter"
			link = "https://twitter.com/devtrax"

		[[params.footer.social]]
			icon = "fa-facebook"
			link = "https://www.facebook.com/devtraxio"
		#
		# [[params.footer.social]]
		# 	icon = "fa-linkedin"
		# 	link = "#"
		#
		# [[params.footer.quicklinks]]
		# 	text = "Privacy Policy"
		# 	link = "#"
		#
		# [[params.footer.quicklinks]]
		# 	text = "Terms of Use"
		# 	link = "#"
